name: Deploy Backend to Elastic Beanstalk

#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: |
          cd backend/CFCBackend
          mvn clean install 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'CFCBackend'
          environment_name: 'CFCBackend-env'
          version_label: "deploy-${{ github.sha }}"
          region: us-east-2
          deployment_package: backend/CFCBackend/target/CFCBackend-0.0.1-SNAPSHOT.jar
